### ISSUE TITLE
Transfer repository to intake organization

### ISSUE THREAD

**Issue by andersy005** [intake/intake-thredds#67]
`intake-thredds` has been in a working state for a while, and I was wondering if we could transfer it to the intake GitHub organization so as to increase its visibility. 

@martindurant, are there any checklist or guidelines that need to be followed for a project to be accepted under the intake GitHub organization?

**Comment by martindurant** [comment]
A request is good enough for me. Do you want to wait for any votes in this issue?
After the move, existing permissions in this repo will be maintained.

**Comment by andersy005** [comment]
@martindurant, I am going to transfer the repository shortly

**Comment by andersy005** [comment]
> @martindurant, I am going to transfer the repository shortly

It looks like I'll need your help with this one. I don't have the necessary permissions. I'm getting this error

![Screen Shot 2022-01-12 at 12 43 22 PM](https://user-images.githubusercontent.com/13301940/149210495-5cf27931-46d3-49e4-b689-13b8e86bcd60.png)

**Comment by martindurant** [comment]
done

**Comment by andersy005** [comment]
Awesome! Thank you...
